name: dbt_project
version: 1.0.0
config-version: 2

profile: dbt_project

model-paths:  ["models"]
macro-paths:  ["macros"]
test-paths:   ["tests"]
seed-paths:   ["seeds"]

models:
  dbt_project:
    silver:
      +materialized: view
      +schema: silver
    gold:
      +materialized: table
      +schema: gold